config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "articles#index" # => root_path

  # Defines the root path route ("/")
  #get 'articles/index'
  
  # root "articles#index"
  #get "/articles", to: "articles#index"
  
  # Defines the articles#index path route ("/articles")
  #get "/articles/:id", to: "articles#show"

  #search route
  get "/articles/search", to: "articles#search"


  #all the CRUD route actions
  resources :categories
  resources :users
  resources :places
  

  resources :articles do
    resources :comments
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy

    belongs_to :category, optional: true
    belongs_to :user, optional: true

    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :body, presence: true, length: { minimum: 10, maximum: 300 }
    validates :category_id, presence: true
    
    def self.search(category_name)
        @articles = Article.joins(:category).where("categories.name = ?", category_name)
        #categories = Category.where(name: category_name)
       # @articles = Article.where(category_id: categories.ids)
        return @articles
        
    end
    


end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy

    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  include Visible
end

app/models/concerns/visible.rb
module Visible extend ActiveSupport::Concern
    def archived?
        self.status == "archived"
    end

    VALID_STATUSES = ["public","private","archived"]

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: "public").count
        end
    end
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :works
    has_many :users, through: :works
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    has_many :works
    has_many :places, through: :works

    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    validates :email, length: { minimum: 3, maximum: 50 }
    validates :surname, length: { minimum: 3, maximum: 50 }
    validates :password, presence: true, length: { minimum: 6, maximum: 50 }

    
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    if @article.category_id != nil then
      @category = Category.find(@article.category_id)
    else
      @category = Category.new
      @category.name = "No category"
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    print("XXX")
    print(@article.category_id)

    if @article.save
      redirect_to @article
      print("SAVED")
    else
      print("NOT SAVED")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  
    #Non-standard methon (or maybe method that are in the wrong place)
    def search
      @articles = Article.search(params[:query])

      render "result"
   end
      

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)

        if @category.save
            redirect_to @category
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to @category
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy

        redirect_to root_path, status: :see_other
    end

    
    private
        def category_params
            params.require(:category).permit(:name, :description)
        end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)

        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy

        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
    end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    def index
        @places = Place.all
    end

    def show
        @place = Place.find(params[:id])
        #TODO show che user in this place
    end

    def new
        @place = Place.new
    end

    def create
        @place = Place.new(article_params)

        if @place.save
            redirect_to @place
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @place = Place.find(params[:id])
    end

    def update
        @place = Place.find(params[:id])

        if @place.update(article_params)
            redirect_to @place
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @place = Place.find(params[:id])
        @place.destroy

        redirect_to root_path, status: :see_other
    end

    private
        def article_params
            params.require(:place).permit( :city, :region, :state, :number)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        #TODO: show article written by this user
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to @user
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to root_path, status: :see_other
    end

            
    private
        def user_params
            params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation,:dob, :isadmin)
        end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>

    <% @article.errors.full_messages_for(:title).each do |message| %>
      <%= message %><br>
      <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>

    <% @article.errors.full_messages_for(:body).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
    <%= form.label :category_id %><br>
    <%= form.collection_select :category_id, Category.all, :id, :name %>

    <% @article.errors.full_messages_for(:category_id).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div><br>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>Edit Article</h1>

<%= render "form", article: @article %>
  

app/views/articles/index.html.erb
<h1>TBDBLOG</h1>
<p>This is my first App in RoR!</p>

<%= render :partial => 'layouts/navbar' %>

<p>Our blog has <%= Article.public_count %> public articles</p>

<h2>Search my column names</h2>
<%= form_with url: "articles/search", method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<h2>Articles list</h2>

<ul>
<% @articles.each do |item| %>
  <li> 
    <%= link_to item.title, article_path(item) %>
  </li>
<%  
   end %>
</ul>
<br>
<%= link_to "New article", new_article_path%>

app/views/articles/new.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>New Article</h1>

<%= render "form", article: @article %>
  

app/views/articles/result.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>Search results</h1>
<p>This is my first App in RoR!</p>




<h2>Articles list</h2>

<ul>
<% @articles.each do |item|
    unless item.archived? %>
  <li> 
    <%= link_to item.title, article_path(item) %>
  </li>
<%  end
   end %>
</ul>
<br>
<%= link_to "New article", new_article_path%>

app/views/articles/show.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<p>Category:  <%= @category.name %></p>
<p>Status: <%= @article.status %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= button_to "Destroy", article_path(@article),method: :delete %></li>
  
</ul>

<h2>Comments</h2>
<%= render @article.comments%>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>

     <% @category.errors.full_messages_for(:name).each do |message| %>
      <%= message %><br>
      <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>

    <% @category.errors.full_messages_for(:description).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1> Edit category</h1>

<%= render "form", article: @article%>

app/views/categories/index.html.erb
<h1>Categories</h1>


<%= render :partial => 'layouts/navbar' %>

<ul>
  <% @categories.each do |category| %>
    <li>
     <%= link_to category.name, category_path(category) %>
     <p> <%= category.description %> </p>
    </li>
  <% end %>
</ul>

<%= link_to "New category", new_category_path%>

app/views/categories/new.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>New category</h1>

<%= render "form", category: @category %>
  

app/views/categories/show.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1><%= @category.name %></h1>

<p><%= @category.description %></p>

<ul>
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= button_to "Destroy", category_path(@category),method: :delete %></li>
  
</ul>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>

  <%= button_to "Destroy Comment", [comment.article, comment], method: :delete %>

 
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/places/_form.html.erb
<%= form_with model: @place do |form| %>

    <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>

     <% @place.errors.full_messages_for(:city).each do |message| %>
      <%= message %><br>
      <% end %>
  </div>

    <div>
        <%= form.label :region %><br>
        <%= form.text_field :region %>

        <% @place.errors.full_messages_for(:region).each do |message| %>
        <%= message %><br>
        <% end %>
    </div>

     <div>
        <%= form.label :state %><br>
        <%= form.text_field :state %>

        <% @place.errors.full_messages_for(:state).each do |message| %>
        <%= message %><br>
        <% end %>
    </div>

     <div>
        <%= form.label :number %><br>
        <%= form.number_field :number %>

        <% @place.errors.full_messages_for(:number).each do |message| %>
        <%= message %><br>
        <% end %>
    </div>







  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1> Edit place</h1>

<%= render "form", place: @place%>

app/views/places/index.html.erb
<h1>Places</h1>


<%= render :partial => 'layouts/navbar' %>

<h2>Places list</h2>

<ul>
  <% @places.each do |place| %>
    <li>Name:
      <%= link_to place.city, place_path(place) %>
      <p>City:  <%= place.city %> </p>
      <p>Region:  <%= place.region %> </p>
      <p>State:  <%= place.state %> </p>
    </li>
  <% end %>
</ul>

<%= link_to "New place", new_place_path%>

app/views/places/new.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>New place</h1>

<%= render "form", place: @place %>
  

app/views/places/show.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1><%= @place.city %> <%= @place.region %></h1>

<p>State: <%= @place.state %></p>
<p>Number: <%= @place.number %></p>


<ul>
  <li><%= link_to "Edit", edit_place_path(@place) %></li>
  <li><%= button_to "Destroy", place_path(@place),method: :delete %></li>
  
</ul>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>

     <% @user.errors.full_messages_for(:name).each do |message| %>
      <%= message %><br>
      <% end %>
  </div>

  <div>
    <%= form.label :surname %><br>
    <%= form.text_area :surname %>

    <% @user.errors.full_messages_for(:surname).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
    <%= form.label :dob %><br>
    <%= form.date_field :dob %>

    <% @user.errors.full_messages_for(:dob).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>

    <% @user.errors.full_messages_for(:email).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>

    <% @user.errors.full_messages_for(:password).each do |message| %>
    <%= message %><br>
    <% end %>
  </div>

  <%= form.select :isadmin, ["true", "false"] %>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1> Edit user</h1>

<%= render "form", user: @user%>

app/views/users/index.html.erb
<h1>Users</h1>


<%= render :partial => 'layouts/navbar' %>

<h2>User list</h2>

<ul>
  <% @users.each do |user| %>
    <li>Email:
      <%= link_to user.email, user_path(user) %>
      <p>Name:  <%= user.name %> </p>
      <p>Surname:  <%= user.surname %> </p>
      <p>Date of birth:  <%= user.dob %> </p>
    </li>
  <% end %>
</ul>

<%= link_to "New user", new_user_path%>

app/views/users/new.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1>New user</h1>

<%= render "form", user: @user %>
  

app/views/users/show.html.erb
<%= render :partial => 'layouts/navbar' %>

<h1><%= @user.name %> - <%= @user.surname %></h1>

<p>Email: <%= @user.email %></p>
<p>Date of birth: <%= @user.dob %></p>
<p>Is admin?: <%= @user.isadmin %></p>

<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= button_to "Destroy", user_path(@user),method: :delete %></li>
  
</ul>